spring:
  datasource:
    url: jdbc:mysql://localhost:3306/secondhand_db?&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: secondhand_db
    password: secondhand_db
  jpa:
    open-in-view: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true
server:
  port: 9090


jwt :
  headers: Authorization
  secretKey: a2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbQ==
  expiration: 9600000
  refresh_expiration: 86400000
